### ISSUE TITLE
Unable to run the container

### ISSUE THREAD

**Issue by Elmomoh** [kosmas58/pia-docker#1]
Hi Kosmas58,

First of all, thank you for this great work.

I have followed your W10 installation procedure and I have an issue when I try to run the container (docker-compose up):

_E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

ERROR: Service 'cnil-pia-front' failed to build: The command '/bin/sh -c apt-get update  && apt-get install --no-install -recommends -y     git     ca-certificates     wget     xz-utils     sudo  && apt-get clean' returned a non-zero code: 100_

Can you help me ?

Thanks

Regards

![capture](https://user-images.githubusercontent.com/37218523/37213853-8aebc4ae-23b3-11e8-972b-764a63e87bab.JPG)

**Comment by kosmas58** [comment]
I'm sorry, because I'm not able to reproduce your problem.

1. On my machine I've deleted all Docker containers for PIA and the images that are used to create them. So I was sure to create a new build.
2. I did `git clone` from the master branch of my github repo and cloned it to my desktop.
3. I've made no changes in that directory.
4. It started up Docker.
5. I'd opened the PowerShell on changed directory to .../Desktop/pia-docker
6. After Docker was running, I ran docker-compose up and everything was created without a problem.
